### PR TITLE
foolstools

### PR DESCRIPTION
**Pull request by ffrappo**
# Fool's Tools

_Created by accident, destined to greatness._

Thank you for considering our project!

### CODE REVIEW

**Comment by lingyun92** [comment]
Developers who applied for the program should provide their KuCoin UID in their PR, and KCC will contact them via the email address linked with the UID.

**Comment by ffrappo** [comment]
Thanks, just did:
https://github.com/kcc-community/kcc-grants/pull/7/commits/3c3d121db21dbf19f4119cf96e2f1c4b8e0210ff
Sorry for the delay, the notification ended up in a busy folder.

Il giorno lun 9 ago 2021 alle ore 06:09 Leandre ***@***.***>
ha scritto:

**Comment by lingyun92** [comment]
No email bind on your KUCOIN account, please bind an email.

**Comment by ffrappo** [comment]
> No email bind on your KUCOIN account, please bind an email.

Done.

**Comment by ffrappo** [comment]
> No email bind on your KUCOIN account, please bind an email.

Also submitted ID verification

**Comment by lingyun92** [comment]
> > No email bind on your KUCOIN account, please bind an email.
> 
> Also submitted ID verification

check your email

**Comment by ffrappo** [comment]
Just did, but if there was anything related to this I didn't see it.

Il giorno lun 16 ago 2021 alle ore 10:18 Leandre ***@***.***>
ha scritto:

**Comment by viaweb3** [comment]
email was sent to `francesco@fornacestudio.com`

**Comment by ffrappo** [comment]
> email was sent to `francesco@fornacestudio.com`

Hi, the last mail I see is from Aug 12th, asking to link an email in Kucoin. I replied Aug 12th telling that the linked email is info@fornacestudio.com (for convenience, since that address it's always checked despite individual holidays).

**Pull request merged**
